# Generated by Django 5.0.1 on 2024-02-05 05:44

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('urls', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='text', unique=True)),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('urls', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.TextField()),
                ('text', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('urls', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True)),
                ('additional_news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_dop', to='news.additional_news')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='news.category')),
            ],
        ),
    ]
