# Generated by Django 5.0.1 on 2024-01-19 14:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='urls',
            field=autoslug.fields.AutoSlugField(default='news', unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='urls',
            field=autoslug.fields.AutoSlugField(unique=True),
        ),
    ]
