# Generated by Django 5.0.1 on 2024-01-19 15:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='urls',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
